apiVersion: v1
kind: ServiceAccount
metadata:
  name: clotho-agent
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "clotho.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clotho-agent
  labels:
    {{- include "clotho.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["nodes/stats", "nodes/proxy"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clotho-agent
  labels:
    {{- include "clotho.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: clotho-agent
subjects:
  - kind: ServiceAccount
    name: clotho-agent
    namespace: {{ .Values.namespace }}
