{{- if .Values.auth }}
{{- if .Values.auth.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: clotho-api-key
  namespace: {{ .Values.namespace }}
  labels:
    app: clotho-operator
    plane: data
    {{- include "clotho.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-key: {{ .Values.auth.apiKey | quote }}
{{- end }}
{{- end }}
