[package]
name = "clotho-sdk"
version = "0.0.1-alpha.1"
edition = "2021"

[features]
default = []
batch = ["dep:polars", "dep:arrow"]

[dependencies]
clotho-macros = { path = "../clotho-macros" }
anyhow = "1.0"
async-trait = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["sync", "macros", "io-util", "rt", "time"] }
uuid = { version = "1.0", features = ["v4", "serde"] }
reqwest = { version = "0.11", features = ["json"] }

# Optional dependencies for Batch Engine
polars = { version = "0.36", features = ["lazy", "ndarray", "simd"], optional = true }
arrow = { version = "50.0", optional = true }