apiVersion: core.clotho.run/v1alpha1
kind: Pipeline
metadata:
  name: crawler-reuters
  namespace: default
spec:
  runtime: "wasm"
  mode: "once"
  gitRepository: "https://github.com/brettnesbitt/clotho.git"
  reference: "examples-and-infra"
  path: ".clotho-stockseer/news-crawler"
  config:
    - name: CRAWLER_SOURCE
      value: "Reuters"
    - name: CRAWLER_FEEDS
      value: '[{"url":"https://ir.thomsonreuters.com/rss/news-releases.xml"}]'
    - name: MONGO_URI
      valueFrom:
        secretKeyRef:
          name: stockseer-secrets
          key: mongo-uri
    - name: MONGO_DB
      value: "bluesky_db"
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "200m"
      memory: "128Mi"
  schedule:
    mode: "interval"
    interval: "35m"
