apiVersion: v1
kind: Service
metadata:
  name: clotho-api
  namespace: {{ .Values.namespace }}
  labels:
    app: clotho-api
    plane: control
    {{- include "clotho-system.labels" . | nindent 4 }}
spec:
  selector:
    app: clotho-api
  ports:
    - port: {{ .Values.api.port }}
      targetPort: {{ .Values.api.port }}
      protocol: TCP
