{{- if and (not .Values.mongo.existingSecret) .Values.mongo.uri }}
apiVersion: v1
kind: Secret
metadata:
  name: clotho-mongo-credentials
  namespace: {{ .Values.namespace }}
  labels:
    app: clotho-mongo-credentials
    plane: control
    {{- include "clotho-control.labels" . | nindent 4 }}
type: Opaque
data:
  uri: {{ .Values.mongo.uri | b64enc | quote }}
{{- end }}