FROM alpine:latest
RUN apk add --no-cache python3 curl bash git openssh-client sed
RUN curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-linux-arm.tar.gz && \
    tar -xf google-cloud-cli-linux-arm.tar.gz && \
    ./google-cloud-sdk/install.sh --quiet && \
    rm google-cloud-cli-linux-arm.tar.gz
ENV PATH="/google-cloud-sdk/bin:${PATH}"
