apiVersion: v1
kind: ServiceAccount
metadata:
  name: clotho-agent
  namespace: clotho-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clotho-agent
rules:
  - apiGroups: [""]
    resources: ["nodes/stats", "nodes/proxy"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clotho-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: clotho-agent
subjects:
  - kind: ServiceAccount
    name: clotho-agent
    namespace: clotho-system
