apiVersion: core.clotho.run/v1alpha1
kind: Pipeline
metadata:
  name: daily-idea
  namespace: default
spec:
  gitRepository: "https://github.com/brettnesbitt/clotho.git"
  reference: "examples-and-infra"
  path: "clotho-sdk/examples/daily-idea"
  config:
    - name: CLOTHO_PIPELINE_ID
      value: "daily-idea"
  resources:
    requests:
      cpu: "100m"
      memory: "64Mi"
    limits:
      cpu: "500m"
      memory: "128Mi"
  replicas: 1
  schedule:
    mode: "interval"
    interval: "30s"
